# **Load preprocessed data [-1,1]**

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np 
import pandas as pd 
   
df = pd.read_csv('/content/drive/MyDrive/Perceptron /diabetes_scale.csv')

In [3]:
df.head(25)

,outcome,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,-1,-0.294118,0.487437,0.180328,-0.292929,-1.000000,0.001490,-0.531170,-0.033333
1,1,-0.882353,-0.145729,0.081967,-0.414141,-1.000000,-0.207153,-0.766866,-0.666667
2,-1,-0.058824,0.839196,0.049180,-1.000000,-1.000000,-0.305514,-0.492741,-0.633333
3,1,-0.882353,-0.105528,0.081967,-0.535354,-0.777778,-0.162444,-0.923997,-1.000000
4,-1,-1.000000,0.376884,-0.344262,-0.292929,-0.602837,0.284650,0.887276,-0.600000
5,1,-0.411765,0.165829,0.213115,-1.000000,-1.000000,-0.236960,-0.894962,-0.700000
6,-1,-0.647059,-0.216080,-0.180328,-0.353535,-0.791962,-0.076006,-0.854825,-0.833333
7,1,0.176471,0.155779,-1.000000,-1.000000,-1.000000,0.052161,-0.952178,-0.733333
8,-1,-0.764706,0.979899,0.147541,-0.090909,0.283688,-0.090909,-0.931682,0.066667
9,-1,-0.058824,0.256281,0.573770,-1.000000,-1.000000,-1.000000,-0.868488,0.100000
10,1,-0.529412,0.105528,0.508197,-1.000000,-1.000000,0.120715,-0.903501,-0.700000
11,-1,0.176471,0.688442,0.213115,-1.000000,-1.000000,0.132638,-0.608027,-0.566667
12,1,0.176471,0.396985,0.311475,-1.000000,-1.000000,-0.192250,0.163962,0.200000
13,-1,-0.882353,0.899497,-0.016393,-0.535354,1.000000,-0.102832,-0.726729,0.266667
14,-1,-0.411765,0.668342,0.180328,-0.616162,-0.586288,-0.230999,-0.565329,NaN
15,-1,-0.176471,0.005025,-1.000000,-1.000000,-1.000000,-0.105812,-0.653288,-0.633333
16,-1,-1.000000,0.185930,0.377049,-0.050505,-0.456265,0.365127,-0.596072,-0.666667
17,-1,-0.176471,0.075377,0.213115,-1.000000,-1.000000,-0.117735,-0.849701,-0.666667
18,1,-0.882353,0.035176,-0.508197,-0.232323,-0.803783,0.290611,-0.910333,-0.600000
19,-1,-0.882353,0.155779,0.147541,-0.393939,-0.773050,0.031296,-0.614859,-0.633333
20,1,-0.647059,0.266332,0.442623,-0.171717,-0.444444,0.171386,-0.465414,-0.800000
21,1,-0.058824,-0.005025,0.377049,-1.000000,-1.000000,0.055142,-0.735269,-0.033333
22,-1,-0.176471,0.969849,0.475410,-1.000000,-1.000000,0.186289,-0.681469,-0.333333
23,-1,0.058824,0.195980,0.311475,-0.292929,-1.000000,-0.135618,-0.842015,-0.733333
24,-1,0.294118,0.437186,0.540984,-0.333333,-0.654846,0.090909,-0.849701,NaN

In [4]:
df_rdy = df.dropna(axis=0, how='any', thresh=None, subset=None,inplace=False) #remove nan

In [5]:
df_rdy.head(25)

,outcome,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,-1,-0.294118,0.487437,0.180328,-0.292929,-1.000000,0.001490,-0.531170,-0.033333
1,1,-0.882353,-0.145729,0.081967,-0.414141,-1.000000,-0.207153,-0.766866,-0.666667
2,-1,-0.058824,0.839196,0.049180,-1.000000,-1.000000,-0.305514,-0.492741,-0.633333
3,1,-0.882353,-0.105528,0.081967,-0.535354,-0.777778,-0.162444,-0.923997,-1.000000
4,-1,-1.000000,0.376884,-0.344262,-0.292929,-0.602837,0.284650,0.887276,-0.600000
5,1,-0.411765,0.165829,0.213115,-1.000000,-1.000000,-0.236960,-0.894962,-0.700000
6,-1,-0.647059,-0.216080,-0.180328,-0.353535,-0.791962,-0.076006,-0.854825,-0.833333
7,1,0.176471,0.155779,-1.000000,-1.000000,-1.000000,0.052161,-0.952178,-0.733333
8,-1,-0.764706,0.979899,0.147541,-0.090909,0.283688,-0.090909,-0.931682,0.066667
9,-1,-0.058824,0.256281,0.573770,-1.000000,-1.000000,-1.000000,-0.868488,0.100000
10,1,-0.529412,0.105528,0.508197,-1.000000,-1.000000,0.120715,-0.903501,-0.700000
11,-1,0.176471,0.688442,0.213115,-1.000000,-1.000000,0.132638,-0.608027,-0.566667
12,1,0.176471,0.396985,0.311475,-1.000000,-1.000000,-0.192250,0.163962,0.200000
13,-1,-0.882353,0.899497,-0.016393,-0.535354,1.000000,-0.102832,-0.726729,0.266667
15,-1,-0.176471,0.005025,-1.000000,-1.000000,-1.000000,-0.105812,-0.653288,-0.633333
16,-1,-1.000000,0.185930,0.377049,-0.050505,-0.456265,0.365127,-0.596072,-0.666667
17,-1,-0.176471,0.075377,0.213115,-1.000000,-1.000000,-0.117735,-0.849701,-0.666667
18,1,-0.882353,0.035176,-0.508197,-0.232323,-0.803783,0.290611,-0.910333,-0.600000
19,-1,-0.882353,0.155779,0.147541,-0.393939,-0.773050,0.031296,-0.614859,-0.633333
20,1,-0.647059,0.266332,0.442623,-0.171717,-0.444444,0.171386,-0.465414,-0.800000
21,1,-0.058824,-0.005025,0.377049,-1.000000,-1.000000,0.055142,-0.735269,-0.033333
22,-1,-0.176471,0.969849,0.475410,-1.000000,-1.000000,0.186289,-0.681469,-0.333333
23,-1,0.058824,0.195980,0.311475,-0.292929,-1.000000,-0.135618,-0.842015,-0.733333
25,-1,0.176471,0.256281,0.147541,-0.474747,-0.728132,-0.073025,-0.891546,-0.333333
26,-1,-0.176471,0.477387,0.245902,-1.000000,-1.000000,0.174367,-0.847139,-0.266667

In [6]:
df_rdy.shape

(759, 9)

# **split data**

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
data = np.array(df_rdy)

In [9]:
y = data[:,0] #label

In [10]:
x = data[:,1:9] #data feature

In [11]:
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, random_state=100) #split data by 8:2

In [12]:
x_train.shape

(607, 8)

In [13]:
x_test.shape

(152, 8)

In [14]:
y_train.shape

(607,)

In [15]:
y_test.shape

(152,)

# **Do the perceptrons**

In [16]:
def perceptron_my(dataArr, labelArr, iter=100, learning_rate = 0.1):

    dataMatrix = np.mat(dataArr)
    m, n = np.shape(dataMatrix) #get the size of matrix
    w = np.zeros((1, np.shape(dataMatrix)[1])) #initialize weight 0
    b = 0
    lr = learning_rate #initialize learning rate 0.1
    print("m,n=",m,n)
    print("w,b,lr=",w,b,",",lr)
    print("iter=",iter)  #print the parameter

    for j in range(iter):
        for i in range(m): #gradient descent for each sample
            xi = dataMatrix[i]
            yi = labelArr[i]
            if yi * (w * xi.T + b) <= 0: #If the sample is misclassified
                w = w + lr * yi * xi #update w and b
                b = b + lr * yi
    return w, b

In [17]:

def acc(dataArr, labelArr, w, b):
  
    dataMatrix = np.mat(dataArr)
    m, n = np.shape(dataMatrix)
    errorCount = 0 #misclassified points
    for i in range(m):
        xi = dataMatrix[i]
        yi = labelArr[i]
        result =  yi * (w * xi.T + b)
        if result <= 0: # If the sample is misclassified
           errorCount += 1
    acc = 1 - (errorCount / m)

    return acc

In [18]:
w,b = perceptron_my(x_train, y_train, iter=100) #do the perceptron with iter=100, learning rate=0.1

m,n= 607 8
w,b,lr= [[0. 0. 0. 0. 0. 0. 0. 0.]] 0 , 0.1
iter= 100

In [19]:
print(acc(x_test, y_test, w, b))

0.8157894736842105

# **Do Perceptrons by sklearn**

In [20]:
from sklearn.linear_model import Perceptron

In [21]:
perceptron = Perceptron(max_iter=100,eta0 = 0.1) # iter=100, learning rate = 0.1

In [22]:
perceptron.fit(x_train, y_train)

Perceptron(eta0=0.1, max_iter=100)

In [23]:
print(perceptron.coef_) #print weight

[[-0.12940905 -0.53266263  0.20820073 -0.06262784 -0.02884484 -0.41073211
  -0.17839759 -0.05000232]]

In [24]:
perceptron.score(x_test,y_test)

0.7828947368421053

# **test max iter = 8**

In [25]:
w10,b10 = perceptron_my(x_train, y_train, iter = 8) # iter=8,learning rate=0.1

m,n= 607 8
w,b,lr= [[0. 0. 0. 0. 0. 0. 0. 0.]] 0 , 0.1
iter= 8

In [26]:
print(acc(x_test, y_test, w10, b10))

0.7960526315789473

In [27]:
perceptron10 = Perceptron(max_iter=8,eta0 = 0.1) # iter=8,learning rate=0.1

In [28]:
perceptron10.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,

Perceptron(eta0=0.1, max_iter=8)

In [29]:
perceptron10.score(x_test,y_test)

0.6973684210526315

# **test low lr**

In [30]:
w0001,b0001 = perceptron_my(x_train, y_train,learning_rate = 0.0001) # iter=100,learning rate=0.0001

m,n= 607 8
w,b,lr= [[0. 0. 0. 0. 0. 0. 0. 0.]] 0 , 0.0001
iter= 100

In [31]:
print(acc(x_test, y_test, w0001, b0001))

0.8157894736842105

In [32]:
perceptron1 = Perceptron(max_iter=100,eta0 = 0.0001) # iter=100,learning rate=0.0001

In [33]:
perceptron1.fit(x_train, y_train)

Perceptron(eta0=0.0001, max_iter=100)

In [34]:
perceptron1.score(x_test,y_test)

0.7763157894736842

# **using mean to replace the NAN**

In [35]:
df = df.fillna(df.mean())

In [36]:
df[:25]

,outcome,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,-1,-0.294118,0.487437,0.180328,-0.292929,-1.000000,0.001490,-0.531170,-0.033333
1,1,-0.882353,-0.145729,0.081967,-0.414141,-1.000000,-0.207153,-0.766866,-0.666667
2,-1,-0.058824,0.839196,0.049180,-1.000000,-1.000000,-0.305514,-0.492741,-0.633333
3,1,-0.882353,-0.105528,0.081967,-0.535354,-0.777778,-0.162444,-0.923997,-1.000000
4,-1,-1.000000,0.376884,-0.344262,-0.292929,-0.602837,0.284650,0.887276,-0.600000
5,1,-0.411765,0.165829,0.213115,-1.000000,-1.000000,-0.236960,-0.894962,-0.700000
6,-1,-0.647059,-0.216080,-0.180328,-0.353535,-0.791962,-0.076006,-0.854825,-0.833333
7,1,0.176471,0.155779,-1.000000,-1.000000,-1.000000,0.052161,-0.952178,-0.733333
8,-1,-0.764706,0.979899,0.147541,-0.090909,0.283688,-0.090909,-0.931682,0.066667
9,-1,-0.058824,0.256281,0.573770,-1.000000,-1.000000,-1.000000,-0.868488,0.100000
10,1,-0.529412,0.105528,0.508197,-1.000000,-1.000000,0.120715,-0.903501,-0.700000
11,-1,0.176471,0.688442,0.213115,-1.000000,-1.000000,0.132638,-0.608027,-0.566667
12,1,0.176471,0.396985,0.311475,-1.000000,-1.000000,-0.192250,0.163962,0.200000
13,-1,-0.882353,0.899497,-0.016393,-0.535354,1.000000,-0.102832,-0.726729,0.266667
14,-1,-0.411765,0.668342,0.180328,-0.616162,-0.586288,-0.230999,-0.565329,-0.599166
15,-1,-0.176471,0.005025,-1.000000,-1.000000,-1.000000,-0.105812,-0.653288,-0.633333
16,-1,-1.000000,0.185930,0.377049,-0.050505,-0.456265,0.365127,-0.596072,-0.666667
17,-1,-0.176471,0.075377,0.213115,-1.000000,-1.000000,-0.117735,-0.849701,-0.666667
18,1,-0.882353,0.035176,-0.508197,-0.232323,-0.803783,0.290611,-0.910333,-0.600000
19,-1,-0.882353,0.155779,0.147541,-0.393939,-0.773050,0.031296,-0.614859,-0.633333
20,1,-0.647059,0.266332,0.442623,-0.171717,-0.444444,0.171386,-0.465414,-0.800000
21,1,-0.058824,-0.005025,0.377049,-1.000000,-1.000000,0.055142,-0.735269,-0.033333
22,-1,-0.176471,0.969849,0.475410,-1.000000,-1.000000,0.186289,-0.681469,-0.333333
23,-1,0.058824,0.195980,0.311475,-0.292929,-1.000000,-0.135618,-0.842015,-0.733333
24,-1,0.294118,0.437186,0.540984,-0.333333,-0.654846,0.090909,-0.849701,-0.599166

In [37]:
dataT = np.array(df)

In [38]:
New_y = dataT[:,0] #label

In [39]:
New_x = dataT[:,1:9] #data feature

In [40]:
Nx_train, Nx_test, Ny_train, Ny_test= train_test_split(New_x,New_y, test_size=0.2, random_state=1) #split data by 8:2

In [41]:
perceptron_mean = Perceptron(max_iter=100,eta0 = 0.1) # test sklearn

In [42]:
perceptron_mean.fit(Nx_train, Ny_train)

Perceptron(eta0=0.1, max_iter=100)

In [43]:
perceptron_mean.score(Nx_test,Ny_test) #test sklearn

0.7662337662337663

In [44]:
ww,bb = perceptron_my(Nx_train, Ny_train) # test my alg

m,n= 614 8
w,b,lr= [[0. 0. 0. 0. 0. 0. 0. 0.]] 0 , 0.1
iter= 100

In [45]:
print(acc(Nx_test, Ny_test, ww, bb)) # test my test

0.7402597402597403